### ISSUE TITLE
Suggested update to README.md

### ISSUE THREAD

**Issue by evoshawkins** [perimetral/deepstream.io-storage-cockroachdb#2]
As the src/connector.js file is written now, the Deepstream config.yml file shown in the example does not work. Connector.js does not look for the ds_ prefix on options vars.

Also the storage name is incorrect. It should be 'cockroachdb' only and not 'deepstream.io-storage-cockroachdb'. Otherwise Deepstream will throw an error 'deepstream.io-storage-deepstream.io-storage-cockroachdb' plugin not found. In other words, Deepstream adds the 'deepstream.io-storage-' prefix onto whatever is supplied in the storage plugin name.

This code works and is what I use.
```
plugins:
  storage:
    name: cockroachdb
    options:
      cockroach: 'postgresql://root@cockroachdb-public:26257?sslmode=disable'
      dbName: 'deepstream'
      tableName: 'deepstream_storage'
      keyType: 'text'
      valueType: 'text'
      splitter: '/'
``` 

### Note: The ds_ prefix options are looked for when environment vars are used to override the options settings.
